name: just_do
description: Write down todos.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  date_format: 1.0.8
  path_provider: any

  cupertino_icons: ^0.1.3

dev_dependencies:
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.0

flutter:
  uses-material-design: true
